[project]
name = "pydantic-ai-retry-fallback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=0.1.3",
    "python-dotenv>=1.1.0",
]
